# Generated by Django 5.1.5 on 2025-02-03 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('userRole', models.CharField(choices=[('forensic_investigator', 'Forensic Investigator'), ('evidence_technician', 'Evidence Technician'), ('legal_officer', 'Legal Officer'), ('supervisor', 'Supervisor'), ('external_auditor', 'External Auditor'), ('system_user', 'System User'), ('admin', 'Admin')], default='not specified', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
