# Generated by Django 5.0.1 on 2025-02-03 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forensic_App', '0002_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('evidence_type', models.CharField(choices=[('DNA', 'DNA'), ('Weapon', 'Weapon'), ('Document', 'Document'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.TextField(help_text='Comma-separated tags for categorization')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='Forensic_App.case')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_collected', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
