# Generated by Django 5.1.6 on 2025-03-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forensic_App', '0002_evidence_is_approved_evidence_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
